# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Autograde

on:
  push:
    branches:
      - '**'   # run on all branches (students push to their own branch)
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5   # optional safety limit

    steps:
      - name: Checkout student branch
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'   # or match your course version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install thrift>=0.16.0
          pip install pytest
          pip install -r requirements.txt || true

      - name: Run pytest
        run: |
          echo "Running tests on branch: ${{ github.ref_name }}"
          pytest -v --maxfail=1 --disable-warnings
